const test=require('node:test'),assert=require('node:assert/strict');
const {criarPagamentosFinanceirosEmpresariais}=require('../functions/enterprise-finance-payments');
const {criarTransferenciasV27}=require('../functions/v27-transferencias');
const {criarFluxosFinanceirosV27}=require('../functions/v27-finance-workflows');
const core=require('../functions/financial-core');
const recurrence=require('../functions/enterprise-finance-recurrences');
const {memoryDb,fixture,HttpsError,user,account}=require('./helpers/critical-fixture.cjs');
const context={auth:{uid:'master'}};
const input=extra=>({contaId:'c1',operacaoId:'op1',valorPagoCentavos:95000,dataPagamento:core.hojeSP(),formaPagamento:'PIX',...extra});
test('Baixa parcial preserva saldo, obrigação, pagamento e auditoria ligados',async()=>{const f=fixture(),r=await f.payments.registrarPagamento(input(),context);assert.equal(r.saldoCentavos,5000);assert.equal(f.db.records.get('financeiro_contas/c1').status,'PARCIALMENTE_PAGA');assert.equal(f.db.records.get('financeiro_pagamentos/'+r.pagamentoId).contaId,'c1');assert.equal([...f.db.records.keys()].filter(k=>k.startsWith('financeiro_auditoria/')).length,1);});
test('Baixa concorrente e retry produzem somente um pagamento',async()=>{const f=fixture(),[a,b]=await Promise.all([f.payments.registrarPagamento(input(),context),f.payments.registrarPagamento(input(),context)]);assert.equal(a.pagamentoId,b.pagamentoId);assert.equal(b.modo,'IDEMPOTENTE');assert.equal(f.db.records.get('financeiro_contas/c1').valorPagoCentavos,95000);assert.equal(b.pagamento.valorPagoCentavos,95000);});
test('Idempotência da baixa rejeita alteração de forma com mesma chave',async()=>{const f=fixture();await f.payments.registrarPagamento(input(),context);await assert.rejects(f.payments.registrarPagamento(input({formaPagamento:'DINHEIRO'}),context),e=>e.code==='already-exists');});
test('Quitação por valor real exige classificação da diferença',async()=>{const f=fixture();await assert.rejects(f.payments.registrarPagamento(input({modoPagamento:'QUITAR_VALOR_REAL'}),context),/motivo/);const r=await f.payments.registrarPagamento(input({modoPagamento:'QUITAR_VALOR_REAL',motivoDiferenca:'DESCONTO'}),context);assert.equal(r.saldoCentavos,0);assert.equal(r.diferencaQuitacaoCentavos,-5000);});
test('Backend exige comprovante quando configurado',async()=>{const f=fixture({'configuracoes_empresas/a':{financeiro:{comprovantePagamentoObrigatorio:true}}});await assert.rejects(f.payments.registrarPagamento(input(),context),/comprovante/);assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,100000);});
test('Backend rejeita comprovante de outro tenant antes de baixar',async()=>{const f=fixture();await assert.rejects(f.payments.registrarPagamento(input({comprovantes:[{path:'tenants/b/financeiro/contas/c1/test.pdf'}]}),context),e=>e.code==='permission-denied');});
test('Backend verifica arquivo real no Storage e preserva comprovante',async()=>{const f=fixture(),receipt={path:'tenants/a/financeiro/contas/c1/test.pdf'};const r=await f.payments.registrarPagamento(input({comprovantes:[receipt]}),context);assert.equal(r.pagamento.comprovantes[0].path,receipt.path);});
test('Backend rejeita datas futuras e inválidas',async()=>{const f=fixture();await assert.rejects(f.payments.registrarPagamento(input({dataPagamento:'2099-01-01'}),context),e=>e.code==='invalid-argument');await assert.rejects(f.payments.registrarPagamento(input({dataPagamento:'2026-02-30'}),context),e=>e.code==='invalid-argument');});
test('Backend rejeita sessão ausente e conta de outra empresa',async()=>{const f=fixture({'financeiro_contas/c1':{...account,clientePlataformaId:'b'}});await assert.rejects(f.payments.registrarPagamento(input(),{}),e=>e.code==='unauthenticated');await assert.rejects(f.payments.registrarPagamento(input(),context),e=>e.code==='permission-denied');});
test('Baixa retroativa aguarda aprovação e decisão confirma pagamento atomicamente',async()=>{const f=fixture({'configuracoes_empresas/a':{financeiro:{baixaRetroativaExigeAprovacao:true}}}),past=core.adicionarDiasISO(core.hojeSP(),-1),r=await f.payments.registrarPagamento(input({dataPagamento:past}),context);assert.equal(r.pendente,true);assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,100000);await f.finance.decidirSolicitacao({solicitacaoId:r.solicitacaoId,decisao:'APROVAR'},context);assert.equal(f.db.records.get('financeiro_solicitacoes/'+r.solicitacaoId).status,'APROVADA');assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,5000);const retry=await f.payments.registrarPagamento(input({dataPagamento:past}),context);assert.equal(retry.modo,'IDEMPOTENTE');assert.ok(retry.pagamento);});
test('Pedido retroativo rejeitado não retorna confirmação financeira e chave não aceita alteração',async()=>{const f=fixture({'configuracoes_empresas/a':{financeiro:{baixaRetroativaExigeAprovacao:true}}}),past=core.adicionarDiasISO(core.hojeSP(),-1),r=await f.payments.registrarPagamento(input({dataPagamento:past}),context);await assert.rejects(f.payments.registrarPagamento(input({dataPagamento:past,formaPagamento:'DINHEIRO'}),context),e=>e.code==='already-exists');await f.finance.decidirSolicitacao({solicitacaoId:r.solicitacaoId,decisao:'REJEITAR',motivo:'Data não autorizada'},context);await assert.rejects(f.payments.registrarPagamento(input({dataPagamento:past}),context),e=>e.code==='failed-precondition');assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,100000);});
test('Estorno de primeira baixa preserva pagamentos posteriores',async()=>{const f=fixture(),r=await f.payments.registrarPagamento(input({valorPagoCentavos:30000}),context);await f.payments.registrarPagamento(input({operacaoId:'op2',valorPagoCentavos:20000}),context);await f.finance.estornarPagamento({pagamentoId:r.pagamentoId,motivo:'Correção da baixa'},context);assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,80000);assert.equal(f.db.records.get('financeiro_contas/c1').valorPagoCentavos,20000);const retry=await f.finance.estornarPagamento({pagamentoId:r.pagamentoId,motivo:'Correção da baixa'},context);assert.equal(retry.modo,'IDEMPOTENTE');assert.equal([...f.db.records.values()].filter(r=>r.acao==='ESTORNAR_PAGAMENTO').length,1);});
test('Estorno de quitação com desconto restaura obrigação original',async()=>{const f=fixture(),r=await f.payments.registrarPagamento(input({modoPagamento:'QUITAR_VALOR_REAL',motivoDiferenca:'DESCONTO'}),context);await f.finance.estornarPagamento({pagamentoId:r.pagamentoId,motivo:'Baixa incorreta'},context);assert.equal(f.db.records.get('financeiro_contas/c1').saldoCentavos,100000);});
test('Transferência direta é idempotente e notifica origem e destino na transação',async()=>{const f=fixture(),data={tipo:'CLIENTE',itemId:'client',destinoAuthUid:'dest',motivo:'Redistribuição',operacaoId:'tr1'},[a,b]=await Promise.all([f.transfers.transferir(data,context),f.transfers.transferir(data,context)]);assert.equal(a.pendente,false);assert.equal(b.modo,'IDEMPOTENTE');assert.equal(f.db.records.get('clientes_operacionais/client').vendedorAuthUid,'dest');assert.equal([...f.db.records.keys()].filter(k=>k.startsWith('direcionamentos_clientes/')).length,1);assert.equal([...f.db.records.values()].filter(r=>r.tipo==='TRANSFERENCIA_RECEBIDA').length,1);assert.equal([...f.db.records.values()].filter(r=>r.tipo==='TRANSFERENCIA_REALIZADA').length,1);});
test('Supervisor solicita transferência, não altera responsável antes de aprovação',async()=>{const f=fixture(),r=await f.transfers.transferir({tipo:'CLIENTE',itemId:'client',destinoAuthUid:'dest',motivo:'Redistribuição',operacaoId:'tr2'},{auth:{uid:'sup'}});assert.equal(r.pendente,true);assert.equal(f.db.records.get('clientes_operacionais/client').vendedorAuthUid,'source');await f.transfers.decidir({solicitacaoId:r.solicitacaoId,decisao:'APROVAR'},context);assert.equal(f.db.records.get('clientes_operacionais/client').vendedorAuthUid,'dest');const retry=await f.transfers.decidir({solicitacaoId:r.solicitacaoId,decisao:'APROVAR'},context);assert.equal(retry.modo,'IDEMPOTENTE');});
test('Supervisor não transfere cliente fora da sua equipe',async()=>{const f=fixture({'clientes_operacionais/client':{clientePlataformaId:'a',equipeId:'e2',vendedorAuthUid:'source'}});await assert.rejects(f.transfers.transferir({tipo:'CLIENTE',itemId:'client',destinoAuthUid:'dest',motivo:'Redistribuição'},{auth:{uid:'sup'}}),e=>e.code==='permission-denied');});
test('Aprovação não transfere cliente cuja origem mudou após solicitação',async()=>{const f=fixture(),r=await f.transfers.transferir({tipo:'CLIENTE',itemId:'client',destinoAuthUid:'dest',motivo:'Redistribuição',operacaoId:'tr3'},{auth:{uid:'sup'}});f.db.records.set('clientes_operacionais/client',{...f.db.records.get('clientes_operacionais/client'),vendedorAuthUid:'other'});await assert.rejects(f.transfers.decidir({solicitacaoId:r.solicitacaoId,decisao:'APROVAR'},context),/responsabilidade/);});
test('Transferência rejeita destino inativo ou de outra empresa',async()=>{for(const dest of [{...user('dest','vendedor'),status:'INATIVO'},{...user('dest','vendedor'),clientePlataformaId:'b'}]){const f=fixture({'usuarios/dest':dest});await assert.rejects(f.transfers.transferir({tipo:'CLIENTE',itemId:'client',destinoAuthUid:'dest',motivo:'Redistribuição'},context),e=>e.code==='failed-precondition');}});
test('Aprovação e rejeição concorrentes não sobrescrevem decisão financeira',async()=>{const f=fixture({'financeiro_solicitacoes/r1':{clientePlataformaId:'a',tipo:'EDICAO',status:'PENDENTE',contaId:'c1',patch:{descricao:'Alterada'},solicitanteAuthUid:'master'}});const result=await Promise.allSettled([f.finance.decidirSolicitacao({solicitacaoId:'r1',decisao:'APROVAR'},context),f.finance.decidirSolicitacao({solicitacaoId:'r1',decisao:'REJEITAR',motivo:'Sem autorização'},context)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.db.records.get('financeiro_solicitacoes/r1').status,'APROVADA');});

test('Recorrências diária semanal quinzenal mensal anual e personalizada avançam corretamente',()=>{for(const [unit,interval,expected]of [['DIA',1,'2026-01-02'],['SEMANA',1,'2026-01-08'],['QUINZENA',1,'2026-01-16'],['MES',1,'2026-02-01'],['ANO',1,'2027-01-01'],['DIA',10,'2026-01-11']])assert.equal(recurrence.nextDate('2026-01-01',unit,interval),expected);assert.equal(recurrence.nextDate('2024-02-29','ANO',1),'2025-02-28');});
test('Recorrência considera fim de semana, feriado e último dia útil',()=>{assert.equal(recurrence.dueDate('2026-10-10',{ajusteFimSemana:'POSTERGAR',feriados:['2026-10-12']}),'2026-10-13');assert.equal(recurrence.dueDate('2026-10-10',{ajusteFimSemana:'ANTECIPAR'}),'2026-10-09');assert.equal(recurrence.dueDate('2026-10-01',{regraDia:'ULTIMO_DIA_UTIL'}),'2026-10-30');assert.equal(recurrence.dueDate('2026-10-01',{regraDia:'NESIMO_DIA_UTIL',nDiaUtil:3}),'2026-10-05');});
test('Geração de recorrência é transacional e não reescreve ocorrência paga',async()=>{const f=fixture({'financeiro_recorrencias/r1':{clientePlataformaId:'a',descricao:'Aluguel',categoriaId:'cat1',valorCentavos:10000,dataInicio:'2026-10-01',proximaGeracao:'2026-10-01',unidade:'MES',intervalo:1,limiteOcorrencias:3,ativo:true,criadoPorAuthUid:'master'},'financeiro_contas/rec_r1_20261001':{clientePlataformaId:'a',status:'PAGA',valorCentavos:10000,valorPagoCentavos:10000,saldoCentavos:0}});const api=recurrence.criarRecorrenciasFinanceiras({db:f.db,functions:{https:{HttpsError}}});const [first,second]=await Promise.all([api.generate('r1',{tenant:'a',uid:'master',until:'2027-01-01'}),api.generate('r1',{tenant:'a',uid:'master',until:'2027-01-01'})]);assert.equal(first.length,2);assert.equal(second.length,0);assert.equal(f.db.records.get('financeiro_contas/rec_r1_20261001').status,'PAGA');assert.equal(f.db.records.get('financeiro_recorrencias/r1').ocorrenciasGeradas,3);});
test('Recorrência sem término continua do cursor e respeita data final quando informada',async()=>{const start=core.hojeSP(),d=n=>core.adicionarDiasISO(start,n),f=fixture({'financeiro_recorrencias/r1':{clientePlataformaId:'a',descricao:'Rotina',categoriaId:'cat1',valorCentavos:1000,dataInicio:start,ajusteFimSemana:'MANTER',unidade:'DIA',intervalo:1,ativo:true,criadoPorAuthUid:'master'}});const api=recurrence.criarRecorrenciasFinanceiras({db:f.db,functions:{https:{HttpsError}}});assert.equal((await api.generate('r1',{tenant:'a',uid:'master',until:d(1)})).length,2);assert.equal((await api.generate('r1',{tenant:'a',uid:'master',until:d(2)})).length,1);f.db.records.set('financeiro_recorrencias/r1',{...f.db.records.get('financeiro_recorrencias/r1'),dataFim:d(3),ajusteFimSemana:'MANTER'});assert.equal((await api.generate('r1',{tenant:'a',uid:'master',until:d(30)})).length,1);});
test('Callable de recorrência rejeita vendedor, sessão ausente e outro tenant',async()=>{const f=fixture({'financeiro_recorrencias/r1':{clientePlataformaId:'b',ativo:true}}),api=recurrence.criarRecorrenciasFinanceiras({db:f.db,functions:{https:{HttpsError}}});await assert.rejects(api.callable({recorrenciaId:'r1'},{}),e=>e.code==='unauthenticated');await assert.rejects(api.callable({recorrenciaId:'r1'},{auth:{uid:'source'}}),e=>e.code==='permission-denied');await assert.rejects(api.callable({recorrenciaId:'r1'},context),e=>e.code==='permission-denied');});

test('Ocorrências diferentes mantêm obrigações distintas ao cair no mesmo dia útil',async()=>{const f=fixture({'financeiro_recorrencias/r1':{clientePlataformaId:'a',descricao:'Diária',categoriaId:'cat1',valorCentavos:1000,dataInicio:'2026-10-10',unidade:'DIA',intervalo:1,ativo:true,criadoPorAuthUid:'master',feriados:['2026-10-12']}}),api=recurrence.criarRecorrenciasFinanceiras({db:f.db,functions:{https:{HttpsError}}});const rows=await api.generate('r1',{tenant:'a',uid:'master',until:'2026-10-12'});assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r.id)).size,3);assert.ok(rows.every(r=>r.vencimento==='2026-10-13'));});

test('Alteração recorrente preserva passado e cadência futura e atualiza modelo',async()=>{const today=core.hojeSP(),next=core.adicionarDiasISO(today,30),old=core.adicionarDiasISO(today,-30),f=fixture({'financeiro_contas/c1':{...account,recorrenciaId:'r1',vencimento:today},'financeiro_contas/c2':{...account,recorrenciaId:'r1',vencimento:next},'financeiro_contas/past':{...account,recorrenciaId:'r1',vencimento:old},'financeiro_recorrencias/r1':{clientePlataformaId:'a',dataInicio:old,proximaGeracao:core.adicionarDiasISO(next,30),valorCentavos:100000},'financeiro_solicitacoes/edit':{clientePlataformaId:'a',status:'PENDENTE',tipo:'EDICAO',contaId:'c1',recorrenciaId:'r1',corteVencimento:today,escopo:'ESTA_E_PROXIMAS',patch:{vencimento:core.adicionarDiasISO(today,2),valorCentavos:120000},solicitanteAuthUid:'master'}});await f.finance.decidirSolicitacao({solicitacaoId:'edit',decisao:'APROVAR'},context);assert.equal(f.db.records.get('financeiro_contas/c2').vencimento,core.adicionarDiasISO(next,2));assert.equal(f.db.records.get('financeiro_contas/past').valorCentavos,100000);assert.equal(f.db.records.get('financeiro_recorrencias/r1').valorCentavos,120000);});
