const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/services/enterprise-finance-service.js'),'utf8');
const file={path:'tenants/a/financeiro/contas/c1/file.pdf',nome:'Comprovante.pdf',url:'https://legacy.invalid/?token=never-use'};
function fixture(extra={}){
  const user={authUid:'u',clientePlataformaId:'a',tipoUsuario:'gerente',status:'ATIVO',acessoLiberado:true,permissoes:{controleFinanceiro:{ver:true}},...extra},events=[],records={'usuarios/u':user,'financeiro_contas/c1':{clientePlataformaId:'a',anexos:[file]}};
  const db={collection:name=>({doc:id=>({get:async options=>{events.push({kind:'get',path:`${name}/${id}`,options});if(records[`${name}/${id}`] instanceof Error)throw records[`${name}/${id}`];return {exists:Boolean(records[`${name}/${id}`]),data:()=>records[`${name}/${id}`]};},update:async data=>{events.push({kind:'update',path:`${name}/${id}`,data});Object.assign(records[`${name}/${id}`],data);}}),add:async()=>({id:'audit'})})};
  const storage={ref:p=>p?{put:async(_f,metadata)=>events.push({kind:'upload',path:p,metadata}),delete:async()=>events.push({kind:'delete',path:p}),getDownloadURL:()=>{throw new Error('URL permanente proibida');}}:{bucket:'test-bucket'}};
  const currentUser={uid:'u',getIdToken:async()=> 'session-token'};
  const global={usuarioLogado:user,db,firebase:{auth:()=>({currentUser}),storage:()=>storage,firestore:{FieldValue:{serverTimestamp:()=>null,arrayUnion:v=>[v]}}},fetch:async(url,options)=>{events.push({kind:'fetch',url,options});return {ok:true,status:200,blob:async()=>new Blob(['%PDF'],{type:'application/pdf'})};}};
  vm.runInNewContext(source,{window:global,console,Intl,Date,Math,Object,Set,Map});return {service:global.IntegroControleFinanceiro,global,records,user,events};
}
for(const [role,read]of [['master_local',true],['financeiro',true],['supervisor_financeiro',true],['supervisor',false],['vendedor',false],['captador',false],['auditor',false],['gerente',false],['master_global',false]])test(`Comprovantes: política local de ${role}`,()=>{const f=fixture({tipoUsuario:role,permissoes:{}});assert.equal(f.service.acessoComprovantes().ler,read);assert.equal(f.service.acessoComprovantes().anexar,false);});
test('Comprovantes: gerente autorizado lê mas não escreve ou exclui',()=>{const f=fixture(),a=f.service.acessoComprovantes();assert.equal(a.ler,true);assert.equal(a.anexar,false);assert.equal(a.excluir,false);});
test('Comprovantes: auditor com permissão continua somente leitura',()=>{const f=fixture({tipoUsuario:'auditor',permissoes:{controleFinanceiro:{ver:true,anexar:true,editar:true}}}),a=f.service.acessoComprovantes();assert.equal(a.ler,true);assert.equal(a.anexar,false);assert.equal(a.excluir,false);});
test('Comprovantes: download consulta usuário e conta no servidor antes do Storage',async()=>{const f=fixture(),blob=await f.service.abrirComprovante('c1',file);assert.equal(blob.size,4);assert.equal(f.events[0].path,'usuarios/u');assert.equal(f.events[1].path,'financeiro_contas/c1');assert.equal(f.events[1].options.source,'server');const fetch=f.events[2];assert.equal(fetch.kind,'fetch');assert.equal(fetch.options.headers.Authorization,'Firebase session-token');assert.equal(fetch.options.cache,'no-store');assert.ok(!fetch.url.includes('token='));});
test('Comprovantes: Firestore associado negado impede requisição ao Storage',async()=>{const f=fixture();f.records['financeiro_contas/c1']=new Error('permission-denied');await assert.rejects(f.service.abrirComprovante('c1',file),/permission-denied/);assert.equal(f.events.some(e=>e.kind==='fetch'),false);});
test('Comprovantes: conta estrangeira ou inexistente impede download',async()=>{for(const account of [null,{clientePlataformaId:'b',anexos:[file]}]){const f=fixture();f.records['financeiro_contas/c1']=account;await assert.rejects(f.service.abrirComprovante('c1',file),/Conta não encontrada/);assert.equal(f.events.some(e=>e.kind==='fetch'),false);}});
test('Comprovantes: conhecer path sem vínculo documental não basta',async()=>{const f=fixture();f.records['financeiro_contas/c1'].anexos=[];await assert.rejects(f.service.abrirComprovante('c1',file),/não pertence/);assert.equal(f.events.some(e=>e.kind==='fetch'),false);});
test('Comprovantes: URL legada não ignora sessão revogada',async()=>{const f=fixture();f.records['usuarios/u']={...f.user,status:'BLOQUEADO'};await assert.rejects(f.service.abrirComprovante('c1',file),/permissão/);assert.equal(f.events.some(e=>e.kind==='fetch'),false);});
test('Comprovantes: Storage negado retorna mensagem amigável',async()=>{const f=fixture();f.global.fetch=async()=>({ok:false,status:403});await assert.rejects(f.service.abrirComprovante('c1',file),/Solicite revisão das permissões/);});
test('Comprovantes: somente leitura não envia nem exclui arquivo',async()=>{const f=fixture();await assert.rejects(f.service.anexarArquivo('c1',{size:4,type:'application/pdf',name:'x.pdf'}),/permissão/);await assert.rejects(f.service.removerArquivo('c1',file),/permissão/);assert.equal(f.events.some(e=>e.kind==='upload'||e.kind==='delete'),false);});
test('Comprovantes: upload autorizado não cria nem persiste URL de download',async()=>{const f=fixture({tipoUsuario:'financeiro',permissoes:{controleFinanceiro:{anexar:true}}}),meta=await f.service.anexarArquivo('c1',{size:4,type:'application/pdf',name:'x.pdf'});assert.equal(meta.url,undefined);assert.ok(meta.path.startsWith('tenants/a/financeiro/contas/c1/'));const upload=f.events.find(e=>e.kind==='upload');assert.equal(upload.metadata.customMetadata.contaId,'c1');assert.equal(upload.metadata.customMetadata.authUid,'u');});
test('Comprovantes: pagamento sem vínculo válido impede upload',async()=>{const f=fixture({tipoUsuario:'financeiro',permissoes:{controleFinanceiro:{anexar:true}}});f.records['financeiro_pagamentos/p1']={clientePlataformaId:'a',contaId:'other'};await assert.rejects(f.service.anexarArquivo('c1',{size:4,type:'application/pdf',name:'x.pdf'},{pagamentoId:'p1'}),/Pagamento não encontrado/);assert.equal(f.events.some(e=>e.kind==='upload'),false);});
test('Comprovantes: troca de sessão durante download invalida resposta',async()=>{const f=fixture();f.global.fetch=async()=>{f.global.usuarioLogado={...f.user,clientePlataformaId:'b'};return {ok:true,blob:async()=>new Blob(['pdf'])};};await assert.rejects(f.service.abrirComprovante('c1',file),/sessão mudou/);});

function renderDetail(access){
  let html='',messages=[];const document={addEventListener(){},getElementById(){return null;}},window={usuarioLogado:{tipoUsuario:'gerente'},IntegroControleFinanceiro:{acessoComprovantes:()=>access},IntegroModuloUtils:{tenant:()=> 'a',openDrawer:(_title,_sub,body)=>html=body,notify:msg=>messages.push(msg)}};
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../js/modules/controle-financeiro-empresarial.js'),'utf8'),{window,document,Intl,Date,setTimeout(){},URL});
  const ui=window.IntegroControleFinanceiroUI;ui.state.accounts=[{id:'c1',descricao:'Conta',status:'PAGA',anexos:[file]}];ui.openDetail('c1');return {ui,window,get html(){return html;},messages};
}
test('Comprovantes UI: usuário sem leitura não vê ação de comprovante',()=>{const f=renderDetail({ler:false,anexar:false,excluir:false});assert.doesNotMatch(f.html,/Ver comprovante|Remover|>Anexar</);});
test('Comprovantes UI: leitor vê comprovante, mas não upload ou exclusão',()=>{const f=renderDetail({ler:true,anexar:false,excluir:false});assert.match(f.html,/Ver comprovante/);assert.doesNotMatch(f.html,/Remover|>Anexar</);});
test('Comprovantes UI: editor autorizado vê as três ações',()=>{const f=renderDetail({ler:true,anexar:true,excluir:true});assert.match(f.html,/Ver comprovante/);assert.match(f.html,/Remover/);assert.match(f.html,/>Anexar</);});
test('Comprovantes UI: Storage negado vira mensagem sem quebrar drawer',async()=>{const f=renderDetail({ler:true,anexar:false,excluir:false});f.window.IntegroControleFinanceiro.abrirComprovante=async()=>{throw Object.assign(new Error('Denied'),{code:'storage/unauthorized'});};await f.ui.downloadAttachment('c1',0);assert.match(f.messages[0],/Solicite revisão das permissões/);assert.match(f.html,/Ver comprovante/);});
