const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'vendedor.html'),'utf8');
function deferred(){let resolve,reject;const promise=new Promise((ok,fail)=>{resolve=ok;reject=fail});return{promise,resolve,reject}}
function bootstrap(){const calls=[];const sales=deferred(),clients=deferred(),secondary=deferred();const env={console:{warn(){}},caixaAberto:()=>true};env.window=env;env.caixaAtual={status:'ABERTO'};for(const key of ['carregarParcelas','carregarPagamentosHistorico','carregarPagamentosHoje','carregarSolicitacoes','carregarHistoricoCobrancas'])env[key]=async()=>{calls.push(key)};env.carregarClientes=()=>{calls.push('clientes');return clients.promise};env.carregarVendas=()=>{calls.push('vendas');return sales.promise};for(const key of ['carregarIndicacoes','carregarCategoriasMovimentacao','carregarNotificacoes'])env[key]=()=>{calls.push(key);return secondary.promise};const start=html.indexOf('  let dadosSecundariosEmAndamento');const end=html.indexOf('  const carregarCaixaAtualOriginal',start);vm.createContext(env);vm.runInContext(html.slice(start,end),env);return{env,calls,sales,clients,secondary}}
test('dados independentes começam juntos e secundários não seguram painel',async()=>{const t=bootstrap();const boot=t.env.carregarTudo({somenteEssenciais:true});assert.ok(t.calls.includes('clientes'));assert.ok(t.calls.includes('vendas'));assert.ok(t.calls.includes('carregarPagamentosHistorico'));assert.ok(!t.calls.includes('carregarParcelas'));assert.ok(!t.calls.includes('carregarNotificacoes'));t.sales.resolve();t.clients.resolve();await boot;assert.ok(t.calls.includes('carregarParcelas'));assert.ok(!t.calls.includes('carregarNotificacoes'));const background=t.env.carregarDadosSecundariosVendedor();assert.ok(t.calls.includes('carregarNotificacoes'));assert.equal(t.env.carregarDadosSecundariosVendedor(),background);t.secondary.resolve();await background});
test('erro essencial não libera painel como se estivesse carregado',async()=>{const t=bootstrap();const boot=t.env.carregarTudo({somenteEssenciais:true});t.sales.reject(Error('rede'));t.clients.resolve();await assert.rejects(boot,/rede/);assert.equal(t.env.__integroCaixaEmVerificacao,false)});
test('erro secundário não rejeita abertura já concluída',async()=>{const t=bootstrap();t.sales.resolve();t.clients.resolve();await t.env.carregarTudo({somenteEssenciais:true});const background=t.env.carregarDadosSecundariosVendedor();t.secondary.reject(Error('rede'));await background});
test('loading não acrescenta pausas artificiais entre as etapas',()=>{const part=html.slice(html.indexOf('async function executarEtapaLoading('),html.indexOf('function manterLoadingPorBloqueio('));assert.doesNotMatch(part,/await esperar/);assert.match(html,/await finalizarLoadingPremiumVendedor\(\);[\s\S]*?carregarDadosSecundariosVendedor/)});
test('verificação canônica do caixa encerra busca sem consultas legadas',async()=>{const calls=[];const env={getBanco:()=>({collection:()=>({where(field){calls.push(field);return this},limit(){return this},get:async()=>({docs:[{id:'c1',data:()=>({status:'ABERTO'})}]})})}),idsUsuarioAtual:()=>['u1','v1'],getTenantAtual:()=> 't1',getUsuarioAtual:()=>({authUid:'u1'}),caixaAbertoValido:()=>true,tempoCaixa:()=>0,console};env.window=env;const start=html.indexOf('  async function buscarCaixaAbertoDoVendedor()'),end=html.indexOf('  async function verificarAcessoCaixaAberto()',start);vm.createContext(env);vm.runInContext(html.slice(start,end),env);assert.equal((await env.buscarCaixaAbertoDoVendedor()).id,'c1');assert.deepEqual(calls,['clientePlataformaId','vendedorAuthUid','status'])});
test('sessão inválida bloqueia retomada e validação recente não repete chamada',async()=>{let valid=true,calls=0;const memory=new Map([['integro:v27:session-id','s1']]);const sdk=()=>{};const env={Date,Uint8Array,Math,console,document:{readyState:'loading',addEventListener(){}},addEventListener(){},setInterval:()=>1,clearInterval(){},localStorage:{getItem:key=>memory.get(key),setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)},firebase:{auth:()=>({currentUser:{uid:'u1'}}),functions:sdk,app:()=>({functions:()=>({httpsCallable:()=>async()=>{calls++;return{data:{ok:valid}}}})})}};env.window=env;vm.runInNewContext(fs.readFileSync(path.join(root,'js/services/v27-session-service.js'),'utf8'),env);assert.equal(await env.IntegroV27Session.resume(),true);assert.equal(await env.IntegroV27Session.resume(),true);assert.equal(calls,1);await env.IntegroV27Session.end({silent:true});memory.set('integro:v27:session-id','s2');valid=false;assert.equal(await env.IntegroV27Session.resume(),false)});

function loginSetup(){const session=deferred(),config=deferred();let configCalls=0;const env={console:{error(){},warn(){}},Date,performance:{now:()=>1},requestAnimationFrame:fn=>fn(),CustomEvent:class{},sessionStorage:{setItem(){},removeItem(){}},location:{pathname:'/index.html'},document:{getElementById:id=>id==='email'?{value:'teste@local'}:id==='senha'?{value:'senha'}:null,querySelector:()=>null,addEventListener(){},dispatchEvent(){}},auth:{signInWithEmailAndPassword:async()=>({user:{uid:'u1'}}),signOut:async()=>{env.signedOut=true}},FirestoreService:{buscarUsuarioPorAuthUid:async()=>({id:'u1',tipoUsuario:'vendedor',clientePlataformaId:'t1'})},State:{setUsuario(){},limparSessao(){}},Validators:{validarUsuario:()=>({ok:true})},UIHelpers:{alerta:m=>{env.error=m}},CONFIG:{ROTAS_POR_TIPO:{vendedor:'vendedor.html'}},IntegroV27Session:{start:()=>session.promise},IntegroConfiguracoesEmpresa:{carregar:()=>{configCalls++;return config.promise}}};env.db={collection:()=>({where(){return this},limit(){return this},get:async()=>({docs:[{id:'aberto',data:()=>({vendedorAuthUid:'u1',clientePlataformaId:'t1',status:'ABERTO'})}]})})};env.window=env;vm.createContext(env);vm.runInContext(fs.readFileSync(path.join(root,'js/auth.js'),'utf8'),env);return{env,session,config,get configCalls(){return configCalls}}}
test('login abre painel após sessão mesmo com configuração secundária lenta',async()=>{const t=loginSetup();const login=t.env.login();await Promise.resolve();await Promise.resolve();assert.equal(t.env.location.href,undefined);t.session.resolve();await login;assert.equal(t.env.location.href,'vendedor.html');assert.equal(t.configCalls,0)});
test('falha ao criar sessão não redireciona ao painel',async()=>{const t=loginSetup();const login=t.env.login();await Promise.resolve();await Promise.resolve();t.session.reject(Error('sessão recusada'));await login;assert.equal(t.env.location.href,undefined);assert.equal(t.env.signedOut,true);assert.match(t.env.error,/sessão recusada/)});
