"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function helpers(){const elements=new Map(),timers=new Map();let sequence=0;const document={getElementById:id=>elements.get(id),createElement:()=>({style:{},dataset:{},children:[],setAttribute(k,v){this[k]=v;},appendChild(e){this.children.push(e);if(e.id)elements.set(e.id,e);},remove(){elements.delete(this.id);}}),addEventListener(){}};document.body=document.createElement();const window={navigator:{onLine:true},setTimeout:task=>{const id=++sequence;timers.set(id,task);return id;},clearTimeout:id=>timers.delete(id),addEventListener(){}};vm.runInNewContext(fs.readFileSync('js/utils/ui-helpers.js','utf8'),{window,document,console});return{ui:window.UIHelpers,window,document,elements,timers};}
test('Toast preserva tipo sucesso/erro e anuncia erro de forma acessível',()=>{const f=helpers();f.ui.alerta('Confirmado','ok');f.ui.alerta('Negado','err');const toasts=f.elements.get('integroToastContainer').children;assert.equal(toasts[0].style.background,'#166534');assert.equal(toasts[1].style.background,'#991b1b');assert.equal(toasts[1]['aria-live'],'assertive');});
test('Erros comuns recebem orientação sem expor detalhes internos',()=>{const {ui}=helpers();assert.match(ui.mensagemErro({code:'functions/unauthenticated',message:'token'}),/Entre novamente/);assert.match(ui.mensagemErro({code:'permission-denied',message:'secret'}),/não possui acesso/);assert.match(ui.mensagemErro({code:'functions/unavailable',message:'secret'}),/internet/);assert.match(ui.mensagemErro({code:'storage/object-not-found'}),/não está mais disponível/);assert.ok(!ui.mensagemErro({code:'functions/internal',message:'secret stack https://server'}).includes('secret'));});
test('Debounce mantém somente última busca e permite cancelamento',()=>{const f=helpers(),calls=[],search=f.ui.debounce(value=>calls.push(value));search('a');search('ab');search('abc');assert.equal(f.timers.size,1);[...f.timers.values()][0]();assert.deepEqual(calls,['abc']);search('abcd');search.cancel();assert.equal(f.timers.size,0);});
test('Próxima cobrança mantém previsão do dia mesmo após visita confirmada',()=>{const api=require('../js/vendedor-operacao');const summary=api.resumoHoje({carteira:[{vendaId:'s',clienteNome:'Cliente',comCobrancaHoje:true,valorParcela:60,pendenteHoje:false,pagoHoje:true},{vendaId:'s2',clienteNome:'Amanhã',comCobrancaHoje:false,valorParcela:80}]});assert.equal(summary.previstoHoje,60);assert.equal(summary.proxima,null);});
test('Notificação de aprovação abre a solicitação correspondente',async()=>{const calls=[],window={IntegroNavegacaoUnificada:{abrirPorId:id=>calls.push(id)},IntegroCentralGestao:{render:()=>calls.push('render'),openRequest:async id=>calls.push('request:'+id)}};vm.runInNewContext(fs.readFileSync('js/routers/notification-router.js','utf8'),{window,document:{querySelector:()=>null}});await window.IntegroNotificationRouter.open({entidadeTipo:'SOLICITACAO_TRANSFERENCIA',entidadeId:'r1',rota:{acao:'APROVACOES'}});assert.deepEqual(calls,['dashboard','render','request:r1']);});
test('Notificação de caixa aguarda abrir apenas o caixa indicado',async()=>{const calls=[],window={IntegroNavegacaoUnificada:{abrirPorId:id=>calls.push(id)},IntegroFinanceiroUnificado:{openBox:async id=>calls.push('box:'+id)}};vm.runInNewContext(fs.readFileSync('js/routers/notification-router.js','utf8'),{window,document:{querySelector:()=>null}});await window.IntegroNotificationRouter.open({entidadeTipo:'CAIXA_DIVERGENTE',entidadeId:'b1'});assert.deepEqual(calls,['movimentacoes','box:b1']);});
test('Três índices preparados correspondem às variantes de consulta das solicitações',()=>{const indexes=JSON.parse(fs.readFileSync('firestore.indexes.json','utf8')).indexes.filter(i=>i.collectionGroup==='financeiro_solicitacoes');for(const fields of [['clientePlataformaId','criadoEmTexto'],['clientePlataformaId','solicitanteAuthUid','criadoEmTexto'],['clientePlataformaId','responsavelNovoAuthUid','criadoEmTexto']])assert.ok(indexes.some(i=>JSON.stringify(i.fields.map(f=>f.fieldPath))===JSON.stringify(fields)&&i.fields.at(-1).order==='DESCENDING'));});
test('Formulário financeiro impede duplo envio e mantém erro inline recuperável',async()=>{let reject,calls=0;const button={disabled:false,setAttribute(){},removeAttribute(){}},errorBox={},document={addEventListener(){},getElementById:id=>id==='cfeConfirmAccount'?button:id==='cfeAccountError'?errorBox:id==='cfeFormCategoria'?{value:'A_DEFINIR'}:null,querySelector:()=>null},window={usuarioLogado:{authUid:'u',nome:'Teste'},IntegroModuloUtils:{notify(){}},IntegroControleFinanceiro:{criarConta:()=>{calls++;return new Promise((_,r)=>reject=r);}}};vm.runInNewContext(fs.readFileSync('js/modules/controle-financeiro-empresarial.js','utf8'),{window,document,Date,Intl,setTimeout,clearTimeout});const api=window.IntegroControleFinanceiroUI,first=api.saveAccount();assert.equal(button.disabled,true);await api.saveAccount();assert.equal(calls,1);reject(new Error('Descrição obrigatória.'));await first;assert.equal(button.disabled,false);assert.equal(errorBox.hidden,false);assert.match(errorBox.textContent,/Descrição/);});
