const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {memoryDb,HttpsError,user}=require('./helpers/critical-fixture.cjs');
const {criarAdministracaoV27}=require('../functions/v27-admin');
class SessionError extends HttpsError { constructor(code,message,details){super(code,message);this.details=details;} }
function frontend(status='FECHADO'){
 const state={start:0,resume:0,out:0,validated:0,queries:[],alerts:[]};
 const seller={id:'documento',authUid:'uid',clientePlataformaId:'tenant',tipoUsuario:'vendedor'};
 const box={id:'box',vendedorId:'documento',vendedorAuthUid:'uid',clientePlataformaId:'tenant',status,ativo:true};
 const elements={email:{value:'vendedor@example.test'},senha:{value:'teste'}};
 const env={console:{error(){},warn(){}},Date,performance:{now:()=>0},CustomEvent:class{constructor(type){this.type=type}},location:{pathname:'/index.html',href:'',replace(url){this.href=url}},sessionStorage:{setItem(){},removeItem(){}},State:{setUsuario(){},limparSessao(){state.cleaned=true}},Validators:{validarUsuario:()=>({ok:true})},CONFIG:{ROTAS_POR_TIPO:{vendedor:'master-local.html'},ERROS:{}},FirestoreService:{buscarUsuarioPorAuthUid:async()=>seller},UIHelpers:{alerta:m=>state.alerts.push(m)},auth:{signInWithEmailAndPassword:async()=>({user:{uid:'uid'}}),signOut:async()=>state.out++,onAuthStateChanged:fn=>state.callback=fn},IntegroV27Session:{start:async()=>state.start++,resume:async()=>{state.resume++;return true},end:async()=>{}},document:{getElementById:id=>elements[id],querySelector:()=>null,addEventListener(){},dispatchEvent:e=>{if(e.type==='usuario-validado')state.validated++},body:{classList:{remove(){}}}},db:{collection:()=>{const filters=[];const q={where(f,op,v){filters.push([f,v]);return q},limit(){return q},get:async options=>{state.queries.push({filters,options});if(state.fail)throw Error('offline');return{docs:[{id:'box',data:()=>box}]}}};return q;}}};
 env.window=env;env.caixaAtual={...box,status:'ABERTO'};vm.createContext(env);vm.runInContext(fs.readFileSync(require.resolve('../js/auth.js'),'utf8'),env);return{env,state,box,seller};
}
test('login com caixa fechado ignora cache aberto, encerra autenticação e não cria sessão nem redireciona',async()=>{const t=frontend();await t.env.login();assert.equal(t.state.start,0);assert.equal(t.state.out,1);assert.equal(t.env.location.href,'');assert.match(t.state.alerts[0],/Caixa fechado/);assert.equal(t.state.queries[0].options.source,'server');assert.equal(t.env.caixaAtual,null)});
test('entrada direta no painel com caixa fechado não libera usuario-validado nem retoma sessão',async()=>{const t=frontend();t.env.protegerPagina();await t.state.callback({uid:'uid'});assert.equal(t.state.resume,0);assert.equal(t.state.validated,0);assert.equal(t.state.out,1);assert.match(t.env.location.href,/motivo=caixa-fechado/)});
test('caixa aberto e reaberto liberam login; fechado após login bloqueia nova entrada',async()=>{for(const status of ['ABERTO','REABERTO']){const t=frontend(status);await t.env.login();assert.equal(t.state.start,1);assert.equal(t.env.location.href,'master-local.html');t.box.status='FECHADO';t.env.location.href='';await t.env.login();assert.equal(t.state.start,1);assert.equal(t.env.location.href,'')}});
test('falha de consulta, outro vendedor e caixa inativo não liberam login',async()=>{for(const mode of ['offline','foreign','inactive']){const t=frontend('ABERTO');if(mode==='offline')t.state.fail=true;if(mode==='foreign')t.box.vendedorAuthUid='outro';if(mode==='inactive')t.box.ativo=false;await t.env.login();assert.equal(t.state.start,0);assert.equal(t.state.out,1)}});
test('perfil gerencial entra sem exigir caixa pessoal',async()=>{const t=frontend();t.seller.tipoUsuario='master_local';t.env.CONFIG.ROTAS_POR_TIPO.master_local='master-local.html';await t.env.login();assert.equal(t.state.start,1);assert.equal(t.state.queries.length,0)});
function backend(status){const db=memoryDb({'usuarios/seller':{...user('seller','usuario_cliente'),cargoChave:'vendedor'},'caixas/box':{clientePlataformaId:'a',vendedorId:'documento_seller',vendedorAuthUid:'seller',status,ativo:true}});return{db,api:criarAdministracaoV27({db,functions:{https:{HttpsError:SessionError}},admin:{}})}};
const context={auth:{uid:'seller'}},input={sessionId:'sessao-vendedor-123456',forceReplace:true};
test('servidor recusa criar sessão de vendedor com caixa fechado ou inexistente',async()=>{for(const status of ['FECHADO','DIVERGENTE','']){const t=backend(status);await assert.rejects(t.api.iniciarSessao(input,context),e=>e.details?.code==='CAIXA_FECHADO');assert.equal((await t.db.collection('sessoes_usuarios').doc('seller').get()).exists,false)}});
test('servidor bloqueia renovação após fechamento e aceita após reabertura',async()=>{const t=backend('ABERTO');await t.api.iniciarSessao(input,context);await t.db.collection('caixas').doc('box').update({status:'FECHADO',ativo:false});await assert.rejects(t.api.validarSessao(input,context),e=>e.details?.code==='CAIXA_FECHADO');await t.db.collection('caixas').doc('box').update({status:'REABERTO',ativo:true});assert.equal((await t.api.validarSessao(input,context)).ok,true)});
