const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root,'vendedor.html'),'utf8');
const open = html.slice(html.indexOf('async function abrirFechamentoCaixa()'),html.indexOf('function contarPendenciasFilaOfflineCaixa'));
const confirm = html.slice(html.indexOf('window.encerrarSessaoAposFechamentoCaixa ='),html.indexOf('function abrirResumoKpi'));
function setup(status='ABERTO') {
 const state={writes:0,logout:0,alerts:[],drawer:null,pending:0,value:'100,00',note:'',fail:false,ended:0};
 const box={id:'c1',vendedorId:'v1',status};
 const snapshot={caixa:box,caixaInicialCentavos:10000,caixaFinalEsperadoCentavos:10000,totalPagamentosCentavos:2000,totalIngressosCentavos:0,totalVendasCentavos:1000,totalGastosCentavos:1000,totalRetiradasCentavos:0,totalRecolhimentosCentavos:0,totalAjustesCentavos:0};
 const context={console:{error(){}},encodeURIComponent,caixaAtual:box,tenantId:'t1',usuarioLogado:{id:'v1',authUid:'v1'},localStorage:{},document:{getElementById:id=>({value:id==='fechamentoValorReal'?state.value:state.note})},
 getPendenciasRotaHoje:()=>Array(state.pending).fill({}),garantirCaixaAberto:()=>['ABERTO','REABERTO'].includes(box.status),notificarIntegro:m=>state.alerts.push(m),atualizarEstadoBotaoFechamento(){},aplicarBloqueioCaixaFechado(){},fecharDrawer(){},
 moeda:v=>'R$ '+Number(v).toFixed(2),campoMoedaHtml:(id,value)=>'<input id="'+id+'" value="'+value+'">',abrirDrawer:(title,subtitle,content)=>{state.drawer={title,content}},converterMoedaBRParaNumero:v=>Number(v.replace(',','.')),contarPendenciasFilaOfflineCaixa:()=>({pendentes:state.offline||0,sincronizando:0}),
 firebase:{auth:()=>({signOut:async()=>{state.ended++}})},IntegroOperacional:{moedaParaCentavos:v=>Math.round(v*100),limparSessaoLocal:()=>{state.cleaned=true}},IntegroLogout:{encerrar:async(fn,opts)=>{state.logout++;state.destination=opts.destino;await fn()}},
 IntegroCaixa:{prepararSnapshotFechamentoCaixa:async()=>snapshot,registrarFechamentoCaixaTransacional:async input=>{if(state.fail)throw Error('gravação rejeitada');if(input.valorInformadoCentavos!==10000&&!input.justificativa)throw Error('Informe justificativa');state.writes++;return{statusFechamento:input.valorInformadoCentavos===10000?'FECHADO':'DIVERGENTE'}}}};context.window=context;vm.createContext(context);vm.runInContext(open+'\n'+confirm,context);return {state,context,box};
}
 test('abre resumo completo com campo vazio para conferência',async()=>{const {state,context}=setup();await context.abrirFechamentoCaixa();assert.equal(state.drawer.title,'Fechar caixa');for(const label of ['Saldo inicial','Recebimentos','Ingressos','Vendas / empréstimos','Despesas','Retiradas','Recolhimentos','Ajustes'])assert.ok(state.drawer.content.includes(label));assert.match(state.drawer.content,/id="fechamentoValorReal" value=""/);assert.match(state.drawer.content,/confirmarFechamentoCaixa/)});
 test('pendências da rota impedem abrir fechamento',async()=>{const {state,context}=setup();state.pending=1;await context.abrirFechamentoCaixa();assert.equal(state.drawer,null)});
 test('campo vazio e fila offline impedem gravar e sair',async()=>{const {state,context}=setup();await context.abrirFechamentoCaixa();state.value='';await context.confirmarFechamentoCaixa();state.value='100,00';state.offline=1;await context.confirmarFechamentoCaixa();assert.equal(state.writes,0);assert.equal(state.logout,0)});
 test('falha de gravação mantém sessão e caixa aberto',async()=>{const {state,context,box}=setup();await context.abrirFechamentoCaixa();state.fail=true;await context.confirmarFechamentoCaixa();assert.equal(state.logout,0);assert.equal(box.status,'ABERTO')});
 for(const status of ['ABERTO','REABERTO'])test('confirma '+status+' e encerra sessão após gravação',async()=>{const {state,context,box}=setup(status);await context.abrirFechamentoCaixa();await context.confirmarFechamentoCaixa();assert.equal(state.writes,1);assert.equal(box.status,'FECHADO');assert.equal(state.logout,1);assert.equal(state.ended,1);assert.equal(state.cleaned,true);assert.match(state.destination,/motivo=caixa-fechado/)});
 test('divergência exige justificativa antes de sair',async()=>{const {state,context}=setup();await context.abrirFechamentoCaixa();state.value='90,00';await context.confirmarFechamentoCaixa();assert.equal(state.logout,0);state.note='Diferença conferida';await context.confirmarFechamentoCaixa();assert.equal(state.writes,1);assert.equal(state.logout,1);assert.match(state.destination,/diverg/)});
 test('preflight não aceita caixa aberto guardado somente em cache',async()=>{const start=html.indexOf('async function verificarAcessoCaixaAberto()');const end=html.indexOf('async function verificarStatusDocumentoCaixaAtual()',start);const env={window:{caixaAtual:{id:'antigo',status:'ABERTO'}},localStorage:{removeItem(){}},buscarCaixaAbertoDoVendedor:async()=>null,forcarLogoutCaixaFechado:async()=>{env.loggedOut=true}};vm.createContext(env);vm.runInContext(html.slice(start,end),env);assert.equal(await env.verificarAcessoCaixaAberto(),false);assert.equal(env.loggedOut,true)});

function financialSetup(status='ABERTO') {
 const records=new Map([['caixas/c1',{clientePlataformaId:'t1',vendedorId:'v1',vendedorAuthUid:'u1',status,saldoAtualCentavos:10000,atualizadoEm:1}]]);
 if(status==='REABERTO')records.set('fechamentos_caixa/fechamento_c1',{clientePlataformaId:'t1',vendedorId:'v1',status:'REABERTO',reaberto:true,totalReaberturas:1});
 let sequence=0;
 function doc(key){return{path:key,id:key.split('/').pop(),get:async()=>({exists:records.has(key),id:key.split('/').pop(),ref:doc(key),data:()=>records.get(key)})}}
 function collection(name,filters=[]){return{doc:id=>doc(name+'/'+(id||'auto'+(++sequence))),where:(key,op,value)=>collection(name,[...filters,[key,op,value]]),limit(){return this},get:async()=>{const docs=[];for(const [key,value]of records)if(key.startsWith(name+'/')&&filters.every(([field,op,wanted])=>op==='in'?wanted.includes(value[field]):value[field]===wanted))docs.push(await doc(key).get());return{docs,forEach:fn=>docs.forEach(fn)}}}}
 const db={collection,runTransaction:async fn=>{const writes=[];const result=await fn({get:ref=>ref.get(),set:(ref,value,opts)=>writes.push(()=>records.set(ref.path,opts?.merge?{...records.get(ref.path),...value}:value)),update:(ref,value)=>writes.push(()=>records.set(ref.path,{...records.get(ref.path),...value}))});writes.forEach(fn=>fn());return result}};
 const firestore=()=>db;firestore.FieldValue={serverTimestamp:()=>2};
 const context={db,firebase:{firestore},console,Intl,Date,localStorage:{getItem:()=>null,removeItem(){}},sessionStorage:{removeItem(){}}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'js/utils/operational.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(root,'js/services/financial-operations.js'),'utf8'),context);
 const snapshot={caixa:{id:'c1',...records.get('caixas/c1')},caixaFinalEsperadoCentavos:10000,dataOperacional:'2026-10-08',pagamentosPendentes:0,pendenciasCobranca:0};
 for(const field of ['caixaInicialCentavos','carteiraInicialCentavos','carteiraFinalCentavos','totalVendasCentavos','totalPagamentosCentavos','totalIngressosCentavos','totalGastosCentavos','totalRetiradasCentavos','totalRecolhimentosCentavos','totalAjustesCentavos','totalCobrancas','totalVisitadas','totalPagas','totalNaoPagas'])snapshot[field]=0;
 const input={caixaId:'c1',clientePlataformaId:'t1',vendedorId:'v1',vendedorAuthUid:'u1',usuario:{id:'v1',authUid:'u1'},valorInformadoCentavos:10000,snapshot};return{records,input,api:context.IntegroCaixa};
}
 test('transação recusa conferência anterior a uma movimentação',async()=>{const {records,input,api}=financialSetup();records.get('caixas/c1').atualizadoEm=3;await assert.rejects(api.registrarFechamentoCaixaTransacional(input),/atualização durante a conferência/);assert.equal(records.get('caixas/c1').status,'ABERTO');assert.equal(records.has('fechamentos_caixa/fechamento_c1'),false)});
 test('refechamento preserva registro anterior e repetição é idempotente',async()=>{const {records,input,api}=financialSetup('REABERTO');const previous=records.get('fechamentos_caixa/fechamento_c1');const result=await api.registrarFechamentoCaixaTransacional(input);assert.equal(result.statusFechamento,'FECHADO');const closure=records.get('fechamentos_caixa/fechamento_c1');assert.equal(closure.reaberto,false);assert.deepEqual(records.get('historico_fechamentos_caixa/'+closure.refechamentoId).fechamentoAnterior,previous);input.snapshot.caixa={...records.get('caixas/c1'),id:'c1'};assert.equal((await api.registrarFechamentoCaixaTransacional(input)).modo,'IDEMPOTENTE')});
